import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";
import { useState } from "react";

export default function Home() {
  const [file, setFile] = useState();
  const [dataArr, setData] = useState();
  const handleOnSubmit = (e) => {
    e.preventDefault();
    callApi();
  };
  async function callApi() {
    const res = await fetch("http://localhost:3000/api/hello", {
      method: "POST",
      body: file,
    });
    const json = await res.json();
    const data = json.name;
    csvToArray(data);
  }

  function csvToArray(data) {
    const csvHeader = data.slice(0, data.indexOf("\n")).split(",");

    const csvRows = data.slice(data.indexOf("\n") + 1).split("\n");

    const array = csvRows.map((i) => {
      const values = i.split(",");
      const obj = csvHeader.reduce((object, header, index) => {
        object[header] = values[index];
        return object;
      }, {});
      return obj;
    });
    console.log(array);
    setData(array);
    console.log(dataArr);
  }
  const handleOnChnage = (e) => {
    console.log(e.target.files);
    setFile(e.target.files[0]);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{ textAlign: "center" }}>
          <h1>REACTJS CSV IMPORT EXAMPLE </h1>
          <form>
            <input type={"file"} accept={".csv"} onChange={handleOnChnage} />
            <button
              onClick={(e) => {
                handleOnSubmit(e);
              }}
            >
              IMPORT CSV
            </button>
          </form>
        </div>
        {dataArr != null ? (
          <div>
            <table>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Url</th>
                  <th>Username</th>
                  <th>Password</th>
                </tr>
              </thead>
              <tbody>
                {dataArr.map((item) => {
                  return (
                    <tr key={"row"}>
                      <td>{item.name}</td>;<td>{item.url}</td>;
                      <td>{item.username}</td>;<td>{item.password}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        ) : (
          ""
        )}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
